pipeline {
    agent any

    environment {
        SONAR_QUBE_SERVER = 'http://sonar.moyu-cloud.internal:9000'
        PROJECT_KEY = 'moyu-cloud-platform'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code from Git...'
                checkout scm
            }
        }

        stage('SonarQube Static Analysis') {
            steps {
                echo 'Running SonarQube Code Scan...'
                script {
                    echo "SonarScan on branch: ${env.BRANCH_NAME}"
                }
            }
        }

        stage('Unit Testing & Coverage') {
            steps {
                echo 'Executing Java JUnit 5 & Node Unit Tests...'
                sh 'mvn clean test'
                sh 'npm test'
            }
        }

        stage('Quality Gate Checklist') {
            steps {
                echo 'Verifying Quality Gate: Coverage >= 70%, Blocker Issues = 0'
            }
        }

        stage('Build & Package') {
            steps {
                echo 'Building Java Spring Boot release package (JAR)...'
                sh 'mvn clean package -DskipTests'
                sh 'npm run build'
            }
        }

        stage('Deploy to Staging/Prod') {
            steps {
                echo 'Deploying Moyu Cloud Platform artifact...'
            }
        }

        stage('Automated Dynamic Tagging & GitHub Push') {
            steps {
                echo 'Generating automated build release tag and syncing to GitHub...'
                script {
                    def buildTime = sh(script: "date +'%Y%m%d-%H%M%S'", returnStdout: true).trim()
                    def tagName = "v1.0.1-build-${buildTime}"
                    echo "Auto-creating and pushing Git Release Tag to GitHub: ${tagName}"
                    sh """
                        git tag -a ${tagName} -m 'Automated build tag generated by Jenkins on ${buildTime}' || true
                        git push origin ${tagName} || true
                    """
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution complete.'
        }
        failure {
            echo 'Pipeline failed. Triggering alert to Moyu Cloud Dev Team.'
        }
    }
}
