sonar.projectKey=moyu-cloud-platform
sonar.projectName=墨云·IP模糊派生灵活生产平台
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=test
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/out/**
sonar.coverage.minimum=70
sonar.issue.blocker.threshold=0
